---
- title: "VulnOptiCON 2026"
  url: /
  nav:
    # - title: Registration
    #   url: "/#Registration"
    - title: Program Overview
      url: "/program"
    - title: Hotel Suggestions
      url: "/hotel"
    - title: Sponsorship Opportunities
      url: "/sponsorship
    - title: Event Sponsors
      url: "/sponsors"
