---
- title: "VulnOptiCON 2026"
  url: /
  nav:
    - title: Registration
      url: "/registration"
    - title: Program
      url: "/program"
    - title: Hotel and Venues
      url: "/hotel"
    - title: Sponsorship
      url: "/sponsorship"
    - title: Event Sponsors
      url: "/sponsors"
